### ISSUE TITLE
Only exports the data visible

### ISSUE THREAD

**Issue by mwentz** [georgeroubie/orchard-export-form-submissions-to-csv#1]
This is more of a limitation than a bug, but this extension can only export the data visible. There are two issues:

- It will only export 20 submissions unless you increase the number of submissions displayed. It is easy enough for any user to increase up to 100 submissions, but past that they would need to know how to change the query string to show more. Overall this is not much of a problem.

- The form submissions screen is set to only show 11 columns, so if your form has more than 11 fields some of the data will not be exported. I don't know of any workarounds for this.

The first issue is minor and something that can be worked around, but the second is a major limitation for this Orchard extension.

**Comment by georgeroubie** [comment]
Hello @mwentz in the version 2.0 you do not have to choose show all, it automatically download every submission. As for your second issue, this is a JavaScript plugin and cannot export anything that is not is the browser. You have to create a module for this. I hope that I helped.
